<#
    gen-index.ps1 — regenerates INDEX.md from script header comments.

    Run from anywhere:  powershell -ExecutionPolicy Bypass -File Tools/gen-index.ps1

    Description source, per .cs file under Assets/Scripts (first match wins):
      1. A "// INDEX: <text>" line anywhere in the first 40 lines (explicit override).
      2. The first sentence of the file's first /// <summary> ... </summary> block.
      3. "(no description)" if neither exists.

    So: edit the header comment of any script, re-run this, INDEX.md updates.
    Keep it cheap — one marker line per file is the token-saving contract.
#>

$ErrorActionPreference = 'Stop'

# Repo root = parent of this script's folder.
$root = Split-Path -Parent $PSScriptRoot
$scriptsDir = Join-Path $root 'Assets\Scripts'
$outFile = Join-Path $root 'INDEX.md'

function Get-Description([string]$path) {
    $lines = Get-Content -LiteralPath $path -Encoding UTF8
    $head = $lines | Select-Object -First 40

    # 1. Explicit // INDEX: marker.
    foreach ($l in $head) {
        if ($l -match '//\s*INDEX:\s*(.+)$') { return $Matches[1].Trim() }
    }

    # 2. First sentence of the first <summary> block.
    $text = ($lines -join "`n")
    if ($text -match '(?s)<summary>(.*?)</summary>') {
        $body = $Matches[1]
        $body = $body -replace '///', ' '        # strip doc-comment prefix
        $body = $body -replace '<[^>]+>', ' '     # strip inner xml tags (<see .../> etc.)
        $body = $body -replace '&amp;', '&'
        $body = ($body -replace '\s+', ' ').Trim()
        if ($body.Length -gt 0) {
            $dot = $body.IndexOf('. ')
            if ($dot -ge 0) { $body = $body.Substring(0, $dot) }
            return $body.TrimEnd('.').Trim()
        }
    }

    return '(no description)'
}

$files = Get-ChildItem -LiteralPath $scriptsDir -Recurse -Filter *.cs | Sort-Object FullName

# Group by folder (relative to Assets/Scripts).
$groups = [ordered]@{}
foreach ($f in $files) {
    $rel = $f.FullName.Substring($scriptsDir.Length).TrimStart('\')
    $dir = Split-Path $rel -Parent
    if ([string]::IsNullOrEmpty($dir)) { $dir = '(root)' }
    if (-not $groups.Contains($dir)) { $groups[$dir] = New-Object System.Collections.ArrayList }
    [void]$groups[$dir].Add([pscustomobject]@{ Name = $f.Name; Desc = (Get-Description $f.FullName) })
}

$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine('# INDEX')
[void]$sb.AppendLine()
[void]$sb.AppendLine('> Auto-generated by `Tools/gen-index.ps1`. Do not edit by hand -- edit the script')
[void]$sb.AppendLine('> header comment (or add a `// INDEX: ...` line) and re-run the generator.')
[void]$sb.AppendLine()
[void]$sb.AppendLine("_$($files.Count) scripts under `Assets/Scripts`._")
[void]$sb.AppendLine()

foreach ($dir in ($groups.Keys | Sort-Object)) {
    [void]$sb.AppendLine("## $dir")
    [void]$sb.AppendLine()
    [void]$sb.AppendLine('| Script | Description |')
    [void]$sb.AppendLine('| --- | --- |')
    foreach ($item in $groups[$dir]) {
        $d = $item.Desc -replace '\|', '\|'
        [void]$sb.AppendLine("| ``$($item.Name)`` | $d |")
    }
    [void]$sb.AppendLine()
}

Set-Content -LiteralPath $outFile -Value $sb.ToString() -Encoding UTF8
Write-Host "Wrote $outFile ($($files.Count) scripts)."
